### ISSUE TITLE
Please add RltvNmbr.vim

### ISSUE THREAD

**Issue by ashleyblackmore** [vim-scraper/vim-scraper.github.com#17]
Is there a reason this is being missed by the scraper? Or perhaps it is blacklisted somewhere?

Link: http://www.vim.org/scripts/script.php?script_id=3458

**Comment by gmarik** [comment]
@ashleyblackmore likely because scraper fails to process the plugin. I won't have details because of lack of the time for investigations. Unlikely to be fixed for same reason.
